
controlLoopRate: 100.0;           # Hz
ctrlMode: 1;                    # 0=ThrusterMapping, 1=classicPidControl, 2=ComputedTorque, 3=Forces
enableThrusters: true;
thrusterPercLimit: 100.0;        # percent

# input saturation limits
surgeMin: -1.5;
surgeMax: 1.5;    # Be careful to make the PID Surge saturation smaller than this values !
swayMin: -1.5;
swayMax: 1.5;
heaveMin: -1.5;
heaveMax: 1.5;
rollRateMin: -0.2;
rollRateMax: 0.2;
pitchRateMin: -0.2;
pitchRateMax: 0.2;
yawRateMin: -0.2;
yawRateMax: 0.2;  # Be careful to make the PID Heading saturation smaller than this values !

thrusterMapping:
{
    pidSurge:
    {
        kp: 1.0;
        ki: 0.4;
        kd: 0.0;
        kff: 0.6;
        n: 10.0;
        tr: 0.5;
        sat: 2.5;
    };
};

classicPidControl:
{
    pidSurge:
    {
        kp: 100.0
        ki: 20.2;
        kd: 2.5;
        kff: 0.0;
        n: 100.0;
        tr: 0.5;
        sat: 4000.0;
    };

    pidSway:
    {
        kp: 100.0
        ki: 25.2;
        kd: 2.5;
        kff: 0.0;
        n: 100.0;
        tr: 0.5;
        sat: 4000.0;
    };

    pidHeave:
    {
        kp: 200.0
        ki: 20.2;
        kd: 25.0;
        kff: 0.0;
        n: 100.0;
        tr: 0.5;
        sat: 4000.0;
    };

    pidRollRate:
    {
        kp: 6.0;#1000.0;
        ki: 0.3;#400.0;
        kd: 0.5;
        kff: 0.0;
        n: 10.0;
        tr: 0.5;
        sat: 560.0; #560.0;
     };

    pidPitchRate:
    {
        kp: 6.0;#1000.0;
        ki: 0.3;#400.0;
        kd: 0.0;
        kff: 0.0;
        n: 10.0;
        tr: 0.5;
        sat: 560.0; #560.0;
     };

     pidYawRate:
     {
        kp: 20.0;#1000.0;
        ki: 2.1;#400.0;
        kd: 0.5;
        kff: 0.0;
        n: 10.0;
        tr: 0.5;
        sat: 560.0; #560.0;
      };
};

